- manifests/install.pp
- manifests/params.pp
- manifests/service.pp
This PR addresses some problems to fix some issues RHEL 7 support.
1. Use `$releasever` instead of the hardcoded `5` in the `baseurl` for the `yumrepo`.
2. Don't force the `upstart` service type if it's a redhat family machine. Let puppet infer that it's `systemd`.
3. Because the chef installer symlinks the systemd service to `/etc/systemd/system/default.target.wants/gitlab-runsvdir.service`, it is not enableable. But it gets started on boot due to it being under `default.target.wants`. The work-around is just to tell puppet not to try and enable the service.
For info, you get the following error in you try to enable the service.
```
Failed to issue method call: No such file or directory
```
> RHEL 7 support

- manifests/config.pp
- manifests/init.pp
- templates/gitlab.rb.erb
I chose gitlab_rails because it matches the name of the configuration section and because it's what's used in README.md.
This resolves #3.
> Remove rails; it's a duplicate of gitlab_rails.

- manifests/init.pp
- manifests/params.pp
- manifests/service.pp
- templates/gitlab.rb.erb
I was testing this on CentOS 6.6 and was running into issues with the service being managed correctly. Since we are using the omnibus package regardless of os, let's use the gitlab-ctl commands all the time. I also experienced an issue where the gitlab.rb template was changing the order of config lines on subsequent runs which would result in unnecessary restarts of gitlab. I changed the template to sort the keys of the hash first and that alleviated the problem. This is nice in general for a clean and organized config.
> Omnibus service fix and template improvement

- manifests/install.pp
If using RedHat 6.5, using $releasever in the yum repository fails with the following message
```
Error: Execution of '/usr/bin/yum -d 0 -e 0 -y list gitlab-ce' returned 1: Error: Cannot retrieve repository metadata (repomd.xml) for repository: gitlab_official. Please verify its path and try again
```
Using the `$::os[release][major]` fact fixes this issue, the stringify_facts option must be set to false for this to work.
> RedHat releasever

- templates/gitlab.rb.erb
For values such as gitlab_rails['backup_upload_connection'] whereby the value should be a hash, using a string or array is not possible as the decorate function wraps the value in quotes. This change maps the hash into a ruby hash suitable for use.
It also means that these values can be specified within hiera
```yaml
gitlab::gitlab_rails:
backup_upload_connection:
provider: 'AWS'
region: 'eu-west-1'
```
> Updated erb template to accomodate for values being hashes

- manifests/config.pp
If using an external database, an additional exec step is needed as outlined in the gitlab documentation:
https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/doc/settings/database.md
> Added check for external database

- spec/classes/init_spec.rb
- templates/gitlab.rb.erb
Currently it's assumed that parameters that are a hash just have a values that are strings. This allows nested hashes to be supported in the template.
> Simplify the decorator for hashes. This allows nested hashes to be output correctly.

- manifests/config.pp
For some reason the reconfigure command will fail on my first puppet run but then resolve itself if the command is run manually.  Adding additional tries during the puppet run resolves the issue.
Here's a snippet of my `puppet agent -t --debug` run.  You can see if needs the second try but I'm not positive as to why
```
Info: /Stage[main]/Gitlab::Config/File[/etc/gitlab/gitlab.rb]: Filebucketed /etc/gitlab/gitlab.rb to main with sum 81d8999f68d05ba8b171595c87cd1028
Notice: /Stage[main]/Gitlab::Config/File[/etc/gitlab/gitlab.rb]/content: content changed '{md5}81d8999f68d05ba8b171595c87cd1028' to '{md5}ae1263a13cf4003ac48f0ee8d1616849'
Info: /Stage[main]/Gitlab::Config/File[/etc/gitlab/gitlab.rb]: Scheduling refresh of Exec[gitlab_reconfigure]
Debug: …
```
> Add retries to gitlab-ctl reconfigure

- manifests/config.pp
- manifests/init.pp
- templates/gitlab.rb.erb
add ability to change manage_accounts hash to disable omnibus account management
tested on centos 7
> allow disabling of omnibus user management

- manifests/init.pp
- manifests/params.pp
- manifests/service.pp
The proposed fix gets a rid of the following error, while provisioning on the Debian-7 VM:
```bash
==> gitlab: Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns: gitlab Reconfigured!
==> gitlab: Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]: Triggered 'refresh' from 1 events
==> gitlab: Error: Execution of '/usr/sbin/update-rc.d gitlab defaults' returned 1: update-rc.d: error: unable to read /etc/init.d/gitlab
==> gitlab: update-rc.d: using dependency based boot sequencing
==> gitlab: Error: /Stage[main]/Gitlab::Service/Service[gitlab]/enable: change from false to true failed: Execution of '/usr/sbin/update-rc.d gitlab defaults' returned 1: update-rc.d: error: unable to read /etc/init.d/gitlab
==> gitlab: update-rc.d: using dependency based boot …
```
> Added the sym-link to the GitLab service executable in the /etc/init.d/.

- .fixtures.yml
- manifests/install.pp
- metadata.json
Fix issues with deprecated values
```
Warning: Scope(Apt::Source[gitlab_official]): $key_source is deprecated and will be removed in the next major release, please use $key => { 'source' => https://packages.gitlab.com/gpg.key } instead.
Warning: Scope(Apt::Source[knot_official]): $include_src is deprecated and will be removed in the next major release, please use $include => { 'src' => true } instead
Warning: Scope(Apt::Source[knot_official]): $include_deb is deprecated and will be removed in the next major release, please use $include => { 'deb' => true } instead
```
> Fix issues with deprecated values in apt::source

- manifests/init.pp
- manifests/install.pp
- manifests/params.pp
- spec/classes/init_spec.rb
Some installations require modification before configuration, thus it
is desirable to be able to unmanage the package in this module, install
and modify it with another, then use this module to configure the
installation.  As an example, it is nice to be able to add additional
omniauth providers after installing the omnibus package, but before
configuring it.
> Add 'manage_package' parameter

- .fixtures.yml
- README.md
- manifests/cirunner.pp
- manifests/runner.pp
- spec/classes/cirunner_spec.rb
From Issue #21 
This change has a new class to setup Gitlab CI Runners
* Install Docker
* Install Gitlab CI Runner Repo
* Install Gitlab CI Multi Runner
* Create runners
It can be used independently from the rest of the Gitlab module
> Gitlab CI Runner

- manifests/params.pp
As the documentation says, that the default for service_enabled is true, this should be true then for all distros.  
This is tested on centos7.1 and the latest gitlab 8.2.3
Issue #27 could be closed with this PR.
No rspec is changed since this kind of test is not covered.
> service enabled for all distro's #27

- manifests/install.pp
Since falling back to $releasever will likely never work as it espands to 7server or 6server everywhere I tested update the module to use the $::operatingsystemmajrelease fact when the is_hash test fails for $::os.  There may be a better way to handle this and I am willing to change it with proper feedback.  I would also like to understand the reasoning behind usng the $:os hash instead of the $::operatingsystemmajrelease fact. Maybe the best way would be to just use this instead?
> Fix this module should work with out having to set the stringify_facts option

- .fixtures.yml
- spec/classes/cirunner_spec.rb
- spec/classes/init_spec.rb
All tests are currently failing in Travis due to STRICT_VARIABLES. Fixed by configuring missing mocked facts.
Also fixes Docker tag in fixtures
> Fix rspec tests

- manifests/custom_hook.pp
- manifests/init.pp
I just migrated from using spuder/puppet-gitlab module to this on and found that there was no support for custom hooks.  this pull request adds spuder/puppet-gitlab/manifest/custom_hooks.pp to this project
> add custom hooks

- manifests/params.pp
```
Error: Could not enable gitlab-runsvdir: Execution of '/sbin/chkconfig --add gitlab-runsvdir' returned 1: service gitlab-runsvdir does not support chkconfig
Error: /Stage[main]/Gitlab::Service/Service[gitlab-runsvdir]/enable: change from false to true failed: Could not enable gitlab-runsvdir: Execution of '/sbin/chkconfig --add gitlab-runsvdir' returned 1: service gitlab-runsvdir does not support chkconfig
```
Fixes #50
> Do not enable service by default on RHEL6

- manifests/config.pp
- manifests/init.pp
- templates/gitlab.rb.erb
Relates to #74, #76 
Credits to #77 
Added missing registry configuration hash. See https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/files/gitlab-config-template/gitlab.rb.template#L319
> Added registry configuration hash option

- manifests/config.pp
- manifests/init.pp
Gives the ability to set the gitlab.rb config file to your own puppet path overriding hiera.
> Allow settings of custom gitlab.rb config file

- manifests/config.pp
- manifests/init.pp
- spec/classes/init_spec.rb
- templates/gitlab.rb.erb
I'm using Gitlab that sit's behind an Nginx reverse proxy, and needed to change the external port. So I've added the `external_port` parameter. Note that to successfully use a different port, you need to add the port to the `external_url` as well. I'm currently using this fork, and it works as expected. I've also added a basic test. Please let me know if you have any concerns.
```puppet
class { 'gitlab':
external_url  => 'http://domain.name:5555',
external_port => 5555,
}
```
> Added external_port parameter

- manifests/config.pp
- manifests/init.pp
- templates/gitlab.rb.erb
In environments that use shared  storage (ex. NFS) required directories might/will already exist. Running puppet module against a setup like that will try to re-create the directories and change their permissions. This stops GitLab from functioning correctly as it is not able to access the filesystem. This commit fixes it by allowing the users to set 'manage_storage_directores[enable]=false' as per https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/doc/settings/configuration.md#disable-storage-directories-management
> Allow "Disable storage directories management"

- lib/facter/gitlab_systemd.rb
- manifests/init.pp
- manifests/params.pp
- manifests/service.pp
- spec/classes/init_spec.rb
* Ensure absent softlink in init.d for operating systems with systemd.
* Updated init.pp description of "service_initd_ensure" to reflect recent changes.
* Added custom fact gitlab_systemd (duplicates fact from camptocamp-systemd, but we dont want full module for just one fact)
* Adds spec to test new systemd functionality
* New fact added to all tests to avoid errors with `STRICT_VARIABLES=yes`
Rebase, squash with tests from #90
> Add systemd_compatibility

- spec/acceptance/class_spec.rb
* Beaker tests when run in a small enough container (such as a Travis box) the Gitlab app can fail with (`Whoops, GitLab is taking too much time to respond.`)
* So we change the regex to see that also, so we can at least see the app has been attempted to start
> Fixes beaker tests

- .travis.yml
- manifests/init.pp
- manifests/params.pp
- manifests/service.pp
- spec/acceptance/class_spec.rb
- spec/acceptance/travis_ci_acceptance_spec.rb
* There are issues running docker in docker in Travis, so lets test the easiest use-case
* Adds a specific Travis spec with the docker workarounds required
* Revert the class spec so tests in Vagrant can still work outside of Travis
> Refactor beaker tests for Travis

- README.md
- manifests/init.pp
- manifests/params.pp
The external_url variable is the only variable that is mandatory for gitlab to install properly. Therefore at it should not have an undef default value. This allows the class to be compiled without a value that will cause the install to fail. 
This PR sets a default value for `external_url` to http://$fqdn. This replaces the undef default value with a the fqdn fact of the node.
> External url

- spec/classes/init_spec.rb
- templates/gitlab.rb.erb
In reference to issue #92.
It appears that no matter how a hash is presented to GitLab, it will not accept it. The field must be presented as YAML, at least in the version I tested.
- The "gitlab_rails['ldap_servers']" field is presented as YAML instead of a hash. In my testing the "to_yaml" call used in the template always produced valid YAML that GitLab accepted.
- Updated the Rspec Test.
- Tested on GitLab 8.13.3, rev 8d79ab3 on CentOS 7
> Fix incorrect syntax in "gitlab_rails['ldap_servers']" field

- manifests/cirunner.pp
cirunner requires xz-utils package for docker to work correctly
> cirunner: add missing hard dependency for xz-utils

- manifests/cirunner.pp
fix missing dependency to apt-transport-https if cirunner is not running on gitlab host itself
> cirunner: fix missing dependency to apt-transport-https

- manifests/cirunner.pp
this allows common runner configurations at a
lower level in the hierarchy and gives the ability
to augment at a higher level, such as a specific node.
> cirunner: merge hashes for runner configuration

- CHANGELOG
- metadata.json
- spec/classes/init_spec.rb
- templates/gitlab.rb.erb
Within the rack_attack_git_basic_auth settings in gitlab_rails the support of integer values is needed.
At the moment all Integers will be interpreted as Strings like this:
gitlab_rails['rack_attack_git_basic_auth'] = {"bantime"=>"3600", "enabled"=>true, "findtime"=>"60", "ip_whitelist"=>["127.0.0.1", "195.65.222.171"], "maxretry"=>"10"}
And after the Puppet run with a gitlab reconfiguration gitlab breaks with the following error, as soon as rack_attack is used:
TypeError (String can't be coerced into Fixnum):
lib/gitlab/auth/ip_rate_limiter.rb:16:in `reset!'
lib/gitlab/auth.rb:51:in `rate_limit!'
lib/gitlab/auth.rb:18:in `find_for_git_client'
app/controllers/projects/git_http_client_controller.rb:117:in `handle_basic_authentication' …
> fixed the use of Integers in gitlab_rails Settings inside gitlab.rb

- CHANGELOG
- metadata.json
- spec/classes/init_spec.rb
- templates/gitlab.rb.erb
Fixed Method for sorting the hashes, so that the ldap hash can be sorted too. If the order of the hash elements in ldap changes at every puppet run, every time a reconfigure and a restart of the gitlab will be triggered.
> fixed method for sorting hashes in gitlab.rb to sort ldap hashes too

- .editorconfig
- manifests/init.pp
- manifests/install.pp
- manifests/params.pp
- manifests/service.pp
- spec/classes/init_spec.rb
- spec/spec_helper.rb
I was preparing to make a merge request for a new feature, and found that I couldn't really add a spec to it for both `deb` and `rpm` without duplicating about 20 LOC in the `spec/classes/init_spec.rb` file.
I used one of the more useful features of the [rspec-puppet-facts](https://github.com/mcanevet/rspec-puppet-facts) gem, to beef up the quality of the tests, and refactored the design to allow new features to be added while typically only requiring 4 new lines of code to test the feature across _all_ supported operating systems.
The overall goal of this PR is to allow us to more easily add new specs by increasing the flexibility of the testing utilities, while simultaneously increasing the likelihood we'll catch a bug for a supported os before it's tagged to a release.
This PR is quite …
> Refactor unit tests to iterate over all supported OS's

- manifests/config.pp
- manifests/init.pp
- spec/classes/init_spec.rb
- templates/gitlab.rb.erb
* previously if you wanted to specify a data directory you would use
git_data_dir.  However this setting was deprecated in 8.10 in favor
of git_data_dirs which is a hash of multiple directories.
* This adds git_data_dirs to the gitlab.rb template and populates
the hash with the legacy git_data_dir if used, as well as also
adding the legacy setting.
> Adds ability to specify git_data_dirs

- README.md
I'm using this module on CentOS 6 and 7, and it works perfectly, so you can probably drop the warning. Your `metadata.json` is already correct.
> Drop warning about RPM support

- manifests/cirunner.pp
- manifests/runner.pp
- spec/classes/cirunner_spec.rb
Should fix https://github.com/vshn/puppet-gitlab/issues/157
> Add 'package_name' param to cirunner class

- README.md
- manifests/cirunner.pp
- spec/acceptance/gitlabci_spec.rb
- spec/acceptance/travis_ci_acceptance_spec.rb
- spec/classes/cirunner_spec.rb
Add support for setting the `metrics_server` parameter in CI Runner. Also installs a newer version of the runner from the proper repo (can be overridden). Closes #166
> Add support for metrics_server in CI Runner

- manifests/install.pp
The yum variable $releasever is '7' in centos, but '7Server' in RHEL.
Also adding the proper GPG based on the edition installed (CE is signed by a different key than EE).  I am not sure if there is a better or more canonical place for their GPG key(s)
> Fix repo URL for RHEL 7.  Enable gpgcheck and add in gitlab-ee key.

- metadata.json
Apt changelog says it's fully backwards compatible. Figure just try a new version number in tests. And it appears the 3.x was skipped altogether.
> apt dep version bump

- manifests/config.pp
Gitlab 10 changes the syntax of the git_data_dirs parameter. If you do not specify git_data_dirs, and only supply git_data_dir, it will put a deprecated syntax in, triggering a warning.
This fixes the syntax. 
Is this ok to merge as is, or does it need some logic to determine if the version specified is <10? 
This fixes #162
> Fix for new git_data_dirs syntax in Gitlab 10

- manifests/config.pp
- manifests/init.pp
- manifests/params.pp
Small pull to add managing the gitlab backup cron job
> Add backup job

- README.md
- manifests/global_hook.pp
- manifests/init.pp
> Introduced in GitLab Shell 4.1.0 and GitLab 8.15.
> 
> Hooks can be also placed in hooks/<hook_name>.d (global).
> add support for chained global hooks

- spec/classes/cirunner_spec.rb
- spec/classes/init_spec.rb
@tobru here are the changes from `rubocop --auto-correct`(#174)
> Fixes via rubocop -a

- manifests/config.pp
- manifests/init.pp
- spec/classes/init_spec.rb
- templates/gitlab.rb.erb
This small PR should be all that's needed to add basic support for the new (gitlab >= 10.5) letsencrypt support.
Please note spec tests are missing, since none of the other hash-based settings seem to have them either.
fixes #199
> add letsencrypt section to gitlab.rb

- manifests/config.pp
I think there were a couple of issues with #155 
This will allow managing the backup cron w/o managing the config file.  Also fixes the SKIP syntax.
> Allow managing backup cron w/o managing the config file

- README.md
- files/gitlab_shell_authorized_keys
- manifests/config.pp
- manifests/init.pp
- spec/classes/init_spec.rb
This enhancement allows for fast lookups for ssh keys for communicating with gitlab instances using git+ssh protocol.
As described in the speed up ssh operations documentation, gitlab has a feature that will allow the gitlab_shell to index authorized_keys for git+ssh connections in the database instead of the authorized_keys file. This can drastically impact the speed of ssh connections when a large number of keys or users are present.
closes #168
> Db indexing for git authorized keys

- manifests/backup.pp
- manifests/config.pp
- manifests/init.pp
This commit moves the backup cronjob to its own class. This ensures that
backup configuration changes do not trigger a Gitlab service restart.
Fixes #204.
> Move backup to its own class

- manifests/config.pp
- manifests/install.pp
the $::os fact hash has been around since 3.5 (and puppet 3 is EOL) this change removes the is_hash dependency provided by stdlib (which is deprecated). 
Supporting references:
https://github.com/puppetlabs/puppetlabs-stdlib#is_hash
Replacements for the is_ functions:
In param block: https://github.com/puppetlabs/puppetlabs-ntp/blob/master/manifests/init.pp#L17-L28
In code block: https://docs.puppet.com/puppet/4.8/lang_expressions.html#regex-or-data-type-match
Note: both of the replacements for is_* are only compatible with puppet 4.0.0 and later, I have updated the metadata.json to reflect this, and I would recommend releasing a new major release version to the forge.
> removing unneeded fact evaluation

- manifests/config.pp
This code block was valid in older versions of gitlab, but in 10.x versions, there are several situations where you would be managing the gitlab service _and_ had configurations in the `postgresql` hash, _and_ have postgresql disabled, or merely not indicate and let the default psql config for the `enable` setting be utilized by omnibus chef.  (for example, gitlab HA configurations for database roles/nodes, or when providing your own psql database)
Additionally, the `git_data_dir` is no longer a valid param, and the postgres configuration doesn't use teh `setup.complete` file at this path any more. This causes gitlab to re-perform setup on each puppet run if you have postgres configurations but don't explictly indicate `enable => true`
Fixes #35 
Fixes #195
> remove auto-execution of gitlab:setup

- manifests/config.pp
- manifests/init.pp
- spec/classes/init_spec.rb
- templates/gitlab.rb.erb
- removed  and documented `git_data_dir` 
- removed the automatic execution of  `gitlab-rake gitlab:setup` if
service_manage = true and postgresql hash has configs but enable is undef || present.
Fixes #159  
Fixes #35
> remove git_data_dir

- manifests/config.pp
- manifests/init.pp
- spec/classes/init_spec.rb
- templates/gitlab.rb.erb
This pull request adds the `roles` configuration item for controlling scaled instances of GitLab Omnibus.
> Add ha roles

- CHANGELOG.md
- metadata.json
Decided to increment to next major version because:
officially dropped puppet 3 support by including param validation
Several other new minor features were also added, which would otherwise make this 1.17.0-rc0.
See CHANGELOG.md in PR for details.
> Prepare 2.0.0 Release

- metadata.json
I'm using this module long time on Ubuntu 16.04 without any errors.
> Add support for Ubuntu 16.04 LTS

- templates/gitlab.rb.erb
Reverts voxpupuli/puppet-gitlab#223
After some discussion in #225, I think it's best to expect valid data types be passed to the module. We could wind up with serious scope creep, and a very untrustworthy decorator, if we we try to program exceptions for non-valid data.
In addition, the original PR takes into consideration `'True'` and `'False'`, but not any other capitalized/cased form of those two words, meaning it only works in very specific circumstances.
Rather than add more exception handling to the decorator, I think it's best to keep the scope of the decorator limited to accepting valid puppet data types. (It should pass a `puppet validate` test).
> Revert "Fix wrong quotation in boolean"

- README.md
- manifests/config.pp
- manifests/init.pp
- manifests/preinstall.pp
- metadata.json
- spec/classes/init_spec.rb
Adds support for managing package post-install steps via the pre-install configuration of a `/etc/gitlab/skip-auto-reconfigure` file (replacing the deprecated `/etc/gitlab/skip-auto-migrations`.
- created an additional manifest for `preinstall.pp`, to handle configurations that need to be present prior to the package installation process. 
- Added documentation to README.md for usage of both the new `skip_auto_reconfigure` class parameter, and the deprecated `skip_auto_migrations` parameter. 
- added a `notify` resource if using the `skip_auto_migrations` parameter to let users know of the deprecation.
Closes #228, #232
> Update auto migrations file

- manifests/cirunner.pp
- manifests/install.pp
- metadata.json
Hi,
since apt-transport-https is in Ubuntu 18.04/Debian 10 just a transitional package it isn't mandatory anymore, the apt-transport-https dependency should be conditional.
Since [puppetlabs-apt](https://github.com/puppetlabs/puppetlabs-apt/blob/master/manifests/source.pp#L32) 4.4.0 handle this correctly I prefer to consume that logic instead build a own.
See:
https://packages.ubuntu.com/bionic/apt-transport-https
https://packages.debian.org/buster/apt-transport-https
> Do not manage apt-transport-https.

- manifests/init.pp
Looks like we missed some of the docs in the comment data of `manifests/init.pp` when we migrated vrom VSHN to voxpupuli.  This PR just removes the old/outdated Authors, Copyright, and examples blocks from the class definition documentation in `manifests/init.pp`
> remove authors, copyright, examples from init.pp

- manifests/init.pp
- manifests/omnibus_config.pp
- spec/classes/init_spec.rb
- templates/gitlab.rb.erb
This PR adds support for configuring the Alertmanager gitlab service.
Documentation for that service is still quite sparse, best I've come across is:
https://prometheus.io/docs/alerting/alertmanager/
Right now our gitlab server is perpetually in error due to an unconfigured alertmanager,
and there's no way to disable it (this commit adds that).
Disabling alertmanager via hiera:
```
gitlab::alertmanager:
enable: false
```
Fixes #266 
Couldn't find any unit tests for other params like this, so I haven't included them here either.
Please let me know :)
> Allow configuration of the alertmanager via puppet.

- data/RedHat.yaml
This updates the `gpgkey` line of the yum repositories as per Gitlab's install docs. At the moment, the `master` branch fails to install because of this. 
The first three commits are PR #271, 227abb5 is the only relevant change here.
I'll rebase this PR if needed when #271 is updated.
> Update gpgkey for yum repos

- data/Debian.yaml
- data/RedHat.yaml
- manifests/omnibus_package_repository.pp
- spec/classes/init_spec.rb
The current `master` branch would generate a `gitlab_official_` repository with an invalid URL. Basically, all edition names (ce/ee) were missing in the repository configuration.
The root of the issue was the attempt at accessing the Puppet catalog's `gitlab::edition` from Hiera. This can't work AFAIK unless users are instructed to only configure the classes through Hiera (undesirable IMO).
I fixed it by providing both CE/EE definitions in Hiera and adding the `ensure` attribute in Puppet to match the requested edition. By managing both repositories, this also ensures that the user cannot end up with a leftover. NB: the Puppet data manipulation step is uglier than it should be, by lack of a Hash -> Hash map function.
The first commit documents the bug, should you prefer a different …
>  fix repositories missing the edition name

- data/family/RedHat.yaml
- spec/classes/init_spec.rb
Somehow, after the #271 and #272 merges we ended up without the GPG key change for gitlab-ce and with `%{lookup()}` calls left in gitlab-ee. This commit fixes the data and adds tests for it.
> fix the repositories as per #271 and #272

- spec/acceptance/gitlab_spec.rb
Travis CI is currently broken.  Fix some issues found while inspecting the situation and attempting to unbreak CI.
No actual issues fixed, but it should help making #290 and #291 pass.
> Fix Continuous Integration

- README.md
- manifests/init.pp
- manifests/service.pp
- spec/classes/init_spec.rb
> remove service dependency cycle

- README.md
The gitlab support information in the README hasn't changed since the very first release. I've added support guidelines for bugs and PR's as they relate to the versions of this puppet module, as well as the gitlab-omnibus product itself.
I also updated the old statement about gitlab 7.10, indicating that if you are using a gitlab package that is _not_ supported by gitlab, then older releases of this module may work better for you.
I tried to make it clear the circumstances for which PR's would be accepted as they relate to breaking or implementing deprecated features of the non-EoL versions of GitLab.
Hopefully this will help clarify the proper usage of this module and what support can be expected based on the version of gitlab-omnibus selected.
> updating module descr and support info

- manifests/init.pp
- manifests/omnibus_config.pp
- spec/classes/init_spec.rb
- templates/gitlab.rb.erb
The `gitlab_monitor` parameter is deprecated for Gitlab > 12.3 and will be removed in 13. This adds the new `gitlab_exporter` parameter.
Fixes #323.
> Deprecate gitlab_monitor in favour of gitlab_exporter

- README.md
- data/family/Debian.yaml
- data/family/RedHat.yaml
- data/os/Ubuntu.yaml
As document in https://docs.gitlab.com/omnibus/update/package_signatures gitlab gpg keys expire soon and needs to be replace with new one.
The old key is valid until 2020-04-15 while is new keys starts at 2020-04-06.
A release of this module in this time slot should useful to avoid some local breaking changes.
This PR is created at 2020-03-28. I except test failures until 2020-04-06.
> Use new gitlab gpg keys for package management

- manifests/init.pp
- manifests/omnibus_config.pp
- spec/classes/init_spec.rb
- templates/gitlab.rb.erb
> Add support for running Gitlab with puma

- REFERENCE.md
- manifests/init.pp
- manifests/omnibus_config.pp
- spec/classes/init_spec.rb
- templates/gitlab.rb.erb
Add pgbouncer_exporter parameter
n/a
> Add pgbouncer_exporter parameter

- tasks/postgres_upgrade.sh
Some bash and command usage improvements. Fixes #356.
> tasks/postgres_upgrade.sh: shellcheck and related fixes

- manifests/service.pp
- spec/acceptance/gitlab_spec.rb
This patch ensures LD_LIBRARY_PATH is unset in the `gitlab-ctl configure`
`exec` resource.
Fixes the LD_LIBRARY_PATH warning emitted at the end of `gitlab-ctl reconfigure`.
As shown in https://travis-ci.org/github/voxpupuli/puppet-gitlab/jobs/739916738
on lines 2089-2090, `gitlab-ctl reconfigure` emits a warning when LD_LIBRARY_PATH
is set. It emits this warning even if that environment variable is empty.  Since
LD_LIBRARY_PATH is always set by the Puppet wrapper script used in the `puppet`
CLI, the `exec` that runs `gitlab-ctl configure` must unset this variable to
avoid the warning message.
> Fix gitlab-ctl reconfigure LD_LIBRARY_PATH warning

- data/family/RedHat.yaml
Add the required name attribute to the yum/dnf repo
```
Repository 'gitlab_official_ee' is missing name in configuration, using id.
```
> Add missing (required) name value for yum repo

- manifests/init.pp
- manifests/omnibus_config.pp
- spec/classes/init_spec.rb
- templates/gitlab.rb.erb
Add support got `geo_logcursor` options in gitlab.rb, see:
https://docs.gitlab.com/ee/development/geo.html#geo-log-cursor-daemon
https://docs.gitlab.com/ee/administration/geo/replication/multiple_servers.html#step-3-configure-the-tracking-database-on-the-secondary-node
n/a
> Add support for geo_logcursor options in gitlab.rb

- REFERENCE.md
- manifests/init.pp
- manifests/omnibus_config.pp
- templates/gitlab.rb.erb
Add support for the gitlab_kas configuration hash. (Kubernetes Agent Server).
gives the ability to configure "Kubernetes Agent Server" on gitlab-ee to manges Gitlab K8s agents.
Gitlab KAS: https://docs.gitlab.com/ee/administration/clusters/kas.html
Available configuration parameters: https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/files/gitlab-config-template/gitlab.rb.template#L1658
> Add support for the gitlab_kas configuration hash.

- manifests/omnibus_package_repository.pp
- spec/classes/init_spec.rb
This PR ensures that apt::update is run before installing Gitlab. Otherwise the installation will fail with `E: Unable to locate package gitlab-(ce|ee)`
> Ensure apt::update is run before installing Gitlab

- README.md
- REFERENCE.md
- manifests/init.pp
- manifests/omnibus_config.pp
- spec/classes/init_spec.rb
- templates/gitlab.rb.erb
Adding support for the gitlab_sshd configuration
Fixes #417
> Adding support for the gitlab_sshd configuration hash

- REFERENCE.md
- manifests/custom_hook.pp
- manifests/global_hook.pp
- spec/defines/custom_hook_spec.rb
Add hashed repository storage support for `custom_hook`. Also add tests for `custom_hook`.
Partial solution to #322
> Improve support for hooks in `@hashed` storage

- data/family/Debian.yaml
On modern debian-based systems, we now get the error "Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details."
With this pull-request I'm trying to fix it.
n/a
> fix apt-key deprecation

- REFERENCE.md
- manifests/init.pp
- manifests/omnibus_config.pp
- spec/classes/init_spec.rb
- templates/gitlab.rb.erb
Trying to get #422 over the line. 
This Pull Request (PR) fixes the following issues
Fixes  https://github.com/voxpupuli/puppet-gitlab/issues/422
Fixes  https://github.com/voxpupuli/puppet-gitlab/issues/372
> Update to support Praefect

- README.md
- REFERENCE.md
- manifests/init.pp
- manifests/install.pp
- spec/classes/init_spec.rb
Introducing the `package_hold`parameter
The `package_hold` parameter allows you to hold the package version in the APT package manager. This is useful when you intend to update the host with 'apt upgrade' (or the bolt task `apt action=upgrade` from puppetlabs-apt) and keep your gitlab instance at the intended version. This prevents unintended upgrading gitlab and perhaps skipping important upgrade path steps.
> Debian: Add support for holding a package

- data/os/Ubuntu.yaml
Same as https://github.com/voxpupuli/puppet-gitlab/pull/432 except for Ubuntu.
> Fix apt-key deprecation on Ubuntu
