Vagrantfile

Adds a friendly vagrant file, useful for testing.

 Adds vagrant file

---

.fixtures.yml
manifests/cirunner.pp
spec/acceptance/gitlabci_spec.rb
spec/classes/cirunner_spec.rb

Added beaker test to check. See #55 for original fixes to get Beaker working.

Add RedHat support for cirunner

---

manifests/cirunner.pp
spec/classes/cirunner_spec.rb

Fix cirunner failure-message for unsupported OS families

Fix cirunner failure-message for unsupported OS families

---

manifests/config.pp
manifests/init.pp
templates/gitlab.rb.erb

This adds support to the registry features introduced in GitLab 8.8, in response to issue #74. This is also my first ever contribution to an open source project, so please be gentle. I couldn't find any directives to how to actually accomplish this so i asked around and tried my best... 😕

Add support for Registry

---

manifests/config.pp
manifests/init.pp
manifests/params.pp

Make config file management configurable

---

.gitignore
.travis.yml
Gemfile
README.md
spec/acceptance/class_spec.rb
spec/acceptance/nodesets/centos-6-docker.yml
spec/acceptance/nodesets/centos-7-docker.yml
spec/acceptance/nodesets/ubuntu-server-1204-docker.yml
spec/acceptance/nodesets/ubuntu-server-1404-docker.yml
spec/spec_helper_acceptance.rb

Add Beaker Travis acceptance tests

---

manifests/cirunner.pp

For issue 
xz-utils incorrect name for CentOS #114

In CentOS land - this is just xz

---

spec/classes/init_spec.rb

This patch fixes the spec test that was broken by the recent update to `templates/gitlab.rb.erb`

Fix spec test

---

manifests/config.pp
manifests/init.pp
templates/gitlab.rb.erb

Added few extra class parameters to manage redis and sentinel. This is useful when you are planning to have a HA installation for redis.

Adding support to confifure redis HA while using omnibus package

---

manifests/config.pp
manifests/init.pp
templates/gitlab.rb.erb

@tobru There was a hash key mismatch in my last pull request. Sorry about that. I've fixed that as well as added Gitaly related stuff.

Added Gitaly related params + fixed template for redis/sentinel related data.

---

Gemfile
Rakefile
manifests/config.pp
manifests/init.pp
templates/gitlab.rb.erb

Adding support for gitlab geo and fixing errors due to missing semantic_puppet gem.
https://travis-ci.org/shaheed121/puppet-gitlab/jobs/252724550

Gitlab geo

---

CHANGELOG
README.md
metadata.json

Transfer module to Vox Pupuli

---

.pre-commit-config.yaml
CHANGELOG
README.md

This is the first release under Vox Pupuli

Release 1.16.0

---

manifests/install.pp

Fixed redhat installation

---

manifests/init.pp
templates/gitlab.rb.erb

Case exception for Boolean values in decorator method inside gitlab.rb.erb template file.
Fixes #222

Fix wrong quotation in boolean

---

Dockerfile
README.md
data/Debian.yaml
data/RedHat.yaml
data/defaults.yaml
hiera.yaml
manifests/init.pp
manifests/install.pp
manifests/omnibus_package_repository.pp
manifests/params.pp
spec/classes/init_spec.rb

244 refactor repository package management

---

manifests/init.pp

remove old param from docs in `manifest/init.pp`

remove doc on manage_package_repo

---

README.md
data/Debian.yaml
data/RedHat.yaml
manifests/init.pp
manifests/install.pp
manifests/omnibus_package_repository.pp

fixed param inheritance in install manifest

---

metadata.json

allow puppetlabs/apt 6.x;  require at least stdlib 4.13.1

---

manifests/global_hook.pp

Replace deprecated validate_* functions

---

.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE.md
.msync.yml
.travis.yml
Dockerfile
Gemfile
Rakefile
examples/init.pp
metadata.json
spec/spec_helper.rb

modulesync 2.7.0 and drop puppet 4

---

manifests/global_hook.pp
spec/defines/global_hook_spec.rb

I introduced a bug in https://github.com/voxpupuli/puppet-gitlab/commit/8164ef89ab91640b43c610696a8cbb80e023c604. This PR fixes it.

Fix broken data type definition

---

.github/CONTRIBUTING.md
.msync.yml
Gemfile
manifests/backup.pp
manifests/custom_hook.pp
spec/spec_helper.rb

modulesync 2.8.0

---

.sync.yml
.travis.yml
metadata.json

Support Debian 10.
no issue created.

Support Debian 10

---

manifests/backup.pp
manifests/custom_hook.pp
manifests/global_hook.pp
manifests/host_config.pp
manifests/init.pp
manifests/install.pp
manifests/omnibus_config.pp
manifests/omnibus_package_repository.pp
manifests/service.pp
spec/defines/global_hook_spec.rb

CI is currently broken because of puppet-lint error. This fixes it.

Fix CI: Fix puppet-lint error (lint_fix)

---

manifests/backup.pp

This ensures that all errors get properly send by mail in events of
failure.

Redirect stderr for backup cron to stdout

---

data/family/Debian.yaml
data/family/RedHat.yaml
data/family/RedHat/6.yaml
data/os/Ubuntu.yaml

Fix warnings reported by yamllint.
Fixes #358.

OS data: YAML linting cleanups

---

CHANGELOG.md
metadata.json

Release of 6.0.1

---

REFERENCE.md

Fix cut and paste error in documentation

---

metadata.json

Drop CentOS 6 from metadata.json / Enable Puppet 7 support / Drop Puppet 5 support

---

README.md

Improve nginx section in README.md.
Add link to gitlab omnibus documentation
refs #371 
don't know if this is sufficient.

README: link to gitlab omnibus nginx documentation

---

metadata.json

also contains https://github.com/voxpupuli/puppet-gitlab/pull/381

Allow latest puppetlabs/apt and puppetlabs/stdlib

---

.github/CONTRIBUTING.md
.github/workflows/ci.yml
.msync.yml
Dockerfile
Gemfile
spec/defines/system_hook_spec.rb

modulesync 4.1.0

---

CHANGELOG.md
REFERENCE.md
metadata.json

release 7.1.0

---

.msync.yml
Gemfile
metadata.json

Remove Debian 9 (EOL)

---

.msync.yml
Gemfile
metadata.json

Add Debian 11 (stable)

---

README.md

Update CI badges to point to Github Actions - Travis is gone

Updated CI badges

---

data/family/RedHat/6.yaml
metadata.json

Drop EoL EL7 support

---

data/family/RedHat.yaml

see:
- https://packages.gitlab.com/gitlab/gitlab-ee/install#manual-rpm
- https://packages.gitlab.com/gitlab/gitlab-ce/install#manual-rpm

New gpg key for RHEL repos.

---

metadata.json

Increase puppetlabs-apt minimum version to 9.2.0
